const categories = [
    { id: 'yemekler', name: 'Yemekler', image: 'images/yemekler.jpg' },
    { id: 'aperatifler', name: 'Aperatifler', image: 'images/aperatifler.jpg' },
    { id: 'salatalar', name: 'Salatalar', image: 'images/salatalar.jpg' },
    { id: 'mezeler', name: 'Mezeler', image: 'images/mezeler.jpg' },
    { id: 'sicak-icecekler', name: 'Sıcak İçecekler', image: 'images/sicak-icecekler.jpg' },
    { id: 'bitki-caylari', name: 'Bitki Çayları', image: 'images/bitki-caylari.jpg' },
    { id: 'soft-icecekler', name: 'Soft İçecekler', image: 'images/soft-icecekler.jpg' },
    { id: 'taze-sikma', name: 'Taze Sıkma İçecekler', image: 'images/taze-sikma.jpg' },
    { id: 'alkollu-icecekler', name: 'Alkollü İçecekler', image: 'images/alkollu-icecekler.jpg', hasSubcategories: true }
];

const alcoholSubcategories = [
    { id: 'biralar', name: 'Biralar', image: 'images/biralar.jpg' },
    { id: 'sarap', name: 'Şarap', image: 'images/sarap.jpg' },
    { id: 'raki', name: 'Rakı', image: 'images/raki.jpg' },
    { id: 'shotlar', name: 'Shotlar', image: 'images/shotlar.jpg' },
    { id: 'kokteyller', name: 'Kokteyller', image: 'images/kokteyller.jpg' },
    { id: 'votka', name: 'Votka', image: 'images/votka.jpg' },
    { id: 'viski', name: 'Viski', image: 'images/viski.jpg' }
];

const menuItems = [
    { id: 1, name: "Efes Malt", price: 180, category: "biralar", image: "images/efes-malt.jpg", description: "Efes Malt" },
    { id: 2, name: "Efes Pilsen", price: 180, category: "biralar", image: "images/efes-pilsen.jpg", description: "Efes Pilsen" },
    { id: 3, name: "Bomonti Filtresiz", price: 135, category: "biralar", image: "images/bomonti-filtresiz.jpg", description: "Bomonti Filtresiz" },
    { id: 4, name: "Becks", price: 195, category: "biralar", image: "images/becks.jpg", description: "Becks" },
    { id: 5, name: "Belfast", price: 195, category: "biralar", image: "images/belfast.jpg", description: "Belfast" },
    { id: 6, name: "Corona", price: 200, category: "biralar", image: "images/corona.jpg", description: "Corona" },
    { id: 7, name: "Bud", price: 135, category: "biralar", image: "images/bud.jpg", description: "Bud" },
    { id: 8, name: "Efes Özel Seri", price: 200, category: "biralar", image: "images/efes-ozel-seri.jpg", description: "Efes Özel Seri" },
    { id: 9, name: "Buzbağ Öküzgözü", price: 350, category: "sarap", image: "images/buzbag-okuzgozu.jpg", description: "Buzbağ Öküzgözü" },
    { id: 10, name: "Buzbağ Elazığ", price: 350, category: "sarap", image: "images/buzbag-elazıg.jpg", description: "Buzbağ Kalecik Karası" },
    { id: 11, name: "Buzbağ Narince", price: 350, category: "sarap", image: "images/buzbag-emir-narince.jpg", description: "Buzbağ Narince" },
    { id: 12, name: "Rakı Tek", price: 270, category: "raki", image: "images/yeni-raki.jpg", description: "Rakı Tek" },
    { id: 13, name: "Rakı Double", price: 320, category: "raki", image: "images/yeni-raki.jpg", description: "Rakı Double" },
    { id: 14, name: "Yeni Rakı 35cl", price: 1100, category: "raki", image: "images/yeni-raki.jpg", description: "Yeni Rakı 35cl" },
    { id: 15, name: "Yeni Rakı 50cl", price: 1500, category: "raki", image: "images/yeni-raki.jpg", description: "Yeni Rakı 50cl" },
    { id: 16, name: "Yeni Rakı 70cl", price: 1300, category: "raki", image: "images/yeni-raki.jpg", description: "Yeni Rakı 70cl" },
    { id: 17, name: "Beylerbeyi Göbek 35cl", price: 1500, category: "raki", image: "images/bira.jpg", description: "Beylerbeyi Göbek 35cl" },
    { id: 18, name: "Beylerbeyi Göbek 50cl", price: 2000, category: "raki", image: "images/bira.jpg", description: "Beylerbeyi Göbek 50cl" },
    { id: 19, name: "Beylerbeyi Göbek 70cl", price: 2500, category: "raki", image: "images/bira.jpg", description: "Beylerbeyi Göbek 70cl" },
    { id: 20, name: "Tekila Shot", price: 120, category: "shotlar", image: "images/tekila.jpg", description: "Tekila Shot" },
    { id: 21, name: "5'li Tekila Shot", price: 500, category: "shotlar", image: "images/tekila.jpg", description: "5'li Tekila Shot" },
    { id: 22, name: "Jagermeister Shot", price: 300, category: "shotlar", image: "images/bira.jpg", description: "Jagermeister Shot" },
    { id: 23, name: "Votka Shot", price: 200, category: "shotlar", image: "images/bira.jpg", description: "Votka Shot" },
    { id: 24, name: "Viski Duble", price: 550, category: "viski", image: "images/viski-duble.jpg", description: "Viski Duble" },
    { id: 25, name: "Viski Tek", price: 370, category: "viski", image: "images/viski-duble.jpg", description: "Viski Tek" },
    { id: 26, name: "Chivas 35cl", price: 1600, category: "viski", image: "images/chivas.jpg", description: "Chivas 35cl" },
    { id: 27, name: "Chivas 50cl", price: 2200, category: "viski", image: "images/chivas.jpg", description: "Chivas 50cl" },
    { id: 28, name: "Chivas 75cl", price: 2600, category: "viski", image: "images/chivas.jpg", description: "Chivas 75cl" },
    { id: 29, name: "Red Label 35cl", price: 1500, category: "viski", image: "images/red-label.jpg", description: "Red Label 35cl" },
    { id: 30, name: "Red Label 70cl", price: 2400, category: "viski", image: "images/red-label.jpg", description: "Red Label 70cl" },
    { id: 31, name: "Istanblue 35cl", price: 800, category: "votka", image: "images/istanblue.jpg", description: "Istanblue 35cl" },
    { id: 32, name: "Istanblue 50cl", price: 1100, category: "votka", image: "images/istanblue.jpg", description: "Istanblue 50cl" },
    { id: 33, name: "Smirnoff 35cl", price: 1000, category: "votka", image: "images/smirnoff.jpg", description: "Smirnoff 35cl" },
    { id: 34, name: "Smirnoff 50cl", price: 1400, category: "votka", image: "images/smirnoff.jpg", description: "Smirnoff 50cl" },
    { id: 35, name: "Köfte", price: 350, category: "yemekler", image: "images/kofte.jpg", description: "Köfte" },
    { id: 36, name: "Kaşarlı Köfte", price: 370, category: "yemekler", image: "images/kasarlı-kofte.jpg", description: "Kaşarlı Köfte" },
    { id: 37, name: "Tavuk Bonfile", price: 250, category: "yemekler", image: "images/tavuk-bonfile.jpg", description: "Tavuk Bonfile" },
    { id: 38, name: "Tavuk Şiş", price: 250, category: "yemekler", image: "images/tavuk-sis.jpg", description: "Tavuk Şiş" },
    { id: 39, name: "Soğan Halkası", price: 110, category: "aperatifler", image: "images/sogan-halkasi.jpg", description: "Soğan Halkası" },
    { id: 40, name: "Patates Kızartması", price: 150, category: "aperatifler", image: "images/patates-kizartmasi.jpg", description: "Patates Kızartması" },
    { id: 41, name: "Sigara Böreği", price: 150, category: "aperatifler", image: "images/sigara-boregi.jpg", description: "Sigara Böreği" },
    { id: 42, name: "Soğuş Tabağı", price: 100, category: "aperatifler", image: "images/sogus-tabagi.jpg", description: "Soğuş Tabağı" },
    { id: 43, name: "Peynirli Salata", price: 200, category: "salatalar", image: "images/peynirli-salata.jpg", description: "Peynirli Salata" },
    { id: 44, name: "Ton Balıklı Salata", price: 200, category: "salatalar", image: "images/ton-balikli-salata.jpg", description: "Ton Balıklı Salata" },
    { id: 45, name: "Çoban Salata", price: 150, category: "salatalar", image: "images/coban-salata.jpg", description: "Çoban Salata" },
    { id: 46, name: "Tavuklu Salata", price: 200, category: "salatalar", image: "images/tavuklu-salata.jpg", description: "Tavuklu Salata" },
    { id: 47, name: "Peynir", price: 130, category: "mezeler", image: "images/peynir.jpg", description: "Peynir" },
    { id: 48, name: "Meyve Tabağı", price: 250, category: "mezeler", image: "images/meyve-tabagi.jpg", description: "Meyve Tabağı" },
    { id: 49, name: "Haydari", price: 150, category: "mezeler", image: "images/haydari.jpg", description: "Haydari" },
    { id: 50, name: "Atom", price: 150, category: "mezeler", image: "images/atom.jpg", description: "Atom" },
    { id: 51, name: "Fava", price: 150, category: "mezeler", image: "images/fava.jpg", description: "Fava" },
    { id: 52, name: "Patatesli Humus", price: 350, category: "mezeler", image: "images/patatesli-humus.jpg", description: "Patatesli Humus" },
    { id: 53, name: "Havuç Tarator", price: 150, category: "mezeler", image: "images/havuc-tarator.jpg", description: "Havuç Tarator" },
    { id: 54, name: "Cacık", price: 150, category: "mezeler", image: "images/cacik.jpg", description: "Cacık" },
    { id: 55, name: "Ordövr Tabağı", price: 250, category: "mezeler", image: "images/ordovr.jpg", description: "Ordövr Tabağı" },
    { id: 56, name: "Köz Biber/Patlıcan", price: 150, category: "mezeler", image: "images/koz-biber.jpg", description: "Köz Biber/Patlıcan" },
    { id: 57, name: "Şakşuka", price: 150, category: "mezeler", image: "images/saksuka.jpg", description: "Şakşuka" },
    { id: 58, name: "Eski Kaşar", price: 120, category: "mezeler", image: "images/eski-kasar.jpg", description: "Eski Kaşar" },
    { id: 59, name: "Fıstık", price: 100, category: "mezeler", image: "images/fistik.jpg", description: "Fıstık" },
    { id: 60, name: "Karışık Çerez", price: 150, category: "mezeler", image: "images/karisik-cerez.jpg", description: "Karışık Çerez" },
    { id: 61, name: "Çay", price: 30, category: "sicak-icecekler", image: "images/cay.jpg", description: "Çay" },
    { id: 62, name: "Fincan Çay", price: 50, category: "sicak-icecekler", image: "images/fincan-cay.jpg", description: "Fincan Çay" },
    { id: 63, name: "Türk Kahvesi", price: 70, category: "sicak-icecekler", image: "images/turk-kahvesi.jpg", description: "Türk Kahvesi" },
    { id: 96, name: "Közde Türk Kahvesi", price: 80, category: "sicak-icecekler", image: "images/kozde-turk-kahvesi.jpg", description: "Közde Türk Kahvesi" },
    { id: 97, name: "Double Türk Kahvesi", price: 100, category: "sicak-icecekler", image: "images/double-turk-kahvesi.jpg", description: "Double Türk Kahvesi" },
    { id: 98, name: "Espresso", price: 110, category: "sicak-icecekler", image: "images/espresso.jpg", description: "Espresso" },
    { id: 64, name: "Americano", price: 110, category: "sicak-icecekler", image: "images/americano.jpg", description: "Americano" },
    { id: 65, name: "Cappuccino", price: 110, category: "sicak-icecekler", image: "images/cappuccino.jpg", description: "Cappuccino" },
    { id: 66, name: "Double Espresso", price: 130, category: "sicak-icecekler", image: "images/double-espresso.jpg", description: "Double Espresso" },
    { id: 67, name: "Latte", price: 110, category: "sicak-icecekler", image: "images/latte.jpg", description: "Latte" },
    { id: 68, name: "Mocha", price: 120, category: "sicak-icecekler", image: "images/mocha.jpg", description: "Mocha" },
    { id: 69, name: "Filtre Kahve", price: 100, category: "sicak-icecekler", image: "images/filtre-kahve.jpg", description: "Filtre Kahve" },
    { id: 70, name: "Sıcak Çikolata", price: 110, category: "sicak-icecekler", image: "images/sicak-cikolata.jpg", description: "Sıcak Çikolata" },
    { id: 71, name: "Ristretto", price: 110, category: "sicak-icecekler", image: "images/ristretto.jpg", description: "Ristretto" },
    { id: 72, name: "Espresso Lungo", price: 110, category: "sicak-icecekler", image: "images/espresso-lungo.jpg", description: "Espresso Lungo" },
    { id: 73, name: "Flat White", price: 110, category: "sicak-icecekler", image: "images/flat-white.jpg", description: "Flat White" },
    { id: 74, name: "Seyahat Kupası", price: 110, category: "sicak-icecekler", image: "images/seyahat-kupasi.jpg", description: "Seyahat Kupası" },
    { id: 75, name: "Ice Latte", price: 110, category: "sicak-icecekler", image: "images/ice-latte.jpg", description: "Ice Latte" },
    { id: 76, name: "Nar Suyu", price: 130, category: "taze-sikma", image: "images/nar-suyu.jpg", description: "Nar Suyu" },
    { id: 77, name: "Portakal Suyu", price: 120, category: "taze-sikma", image: "images/portakal-suyu.jpg", description: "Portakal Suyu" },
    { id: 78, name: "Atom", price: 150, category: "taze-sikma", image: "images/atom-icecegi.jpg", description: "Atom" },
    { id: 79, name: "Ballı Muz", price: 150, category: "taze-sikma", image: "images/balli-muz.jpg", description: "Ballı Muz" },
    { id: 80, name: "Meyve Suyu", price: 100, category: "soft-icecekler", image: "images/meyve-suyu.jpg", description: "Meyve Suyu" },
    { id: 81, name: "Kola", price: 100, category: "soft-icecekler", image: "images/kola.jpg", description: "Kola" },
    { id: 82, name: "Fanta", price: 100, category: "soft-icecekler", image: "images/fanta.jpg", description: "Fanta" },
    { id: 83, name: "Sade Soda", price: 50, category: "soft-icecekler", image: "images/sade-soda.jpg", description: "Sade Soda" },
    { id: 84, name: "Meyveli Soda", price: 50, category: "soft-icecekler", image: "images/meyveli-soda.jpg", description: "Meyveli Soda" },
    { id: 85, name: "Churchill", price: 80, category: "soft-icecekler", image: "images/churchill.jpg", description: "Churchill" },
    { id: 86, name: "Enerji İçeceği", price: 100, category: "soft-icecekler", image: "images/enerji-icecegi.jpg", description: "Enerji İçeceği" },
    { id: 87, name: "Su", price: 25, category: "soft-icecekler", image: "images/su.jpg", description: "Su" },
    { id: 88, name: "Ihlamur", price: 120, category: "bitki-caylari", image: "images/ihlamur.jpg", description: "Ihlamur" },
    { id: 89, name: "Ada Çayı", price: 120, category: "bitki-caylari", image: "images/ada-cayi.jpg", description: "Ada Çayı" },
    { id: 90, name: "Nane Limon", price: 120, category: "bitki-caylari", image: "images/nane-limon.jpg", description: "Nane Limon" },
    { id: 91, name: "Kış Çayı", price: 120, category: "bitki-caylari", image: "images/kis-cayi.jpg", description: "Kış Çayı" },
    { id: 92, name: "Cin Tonik", price: 150, category: "kokteyller", image: "images/cin-tonik.jpg", description: "Cin Tonik" },
    { id: 93, name: "Özel Karışım", price: 150, category: "kokteyller", image: "images/ozel-karisim.jpg", description: "Özel Karışım" },
    { id: 94, name: "Deve Kokteyl", price: 150, category: "kokteyller", image: "images/deve-kokteyl.jpg", description: "Deve Kokteyl" },
    { id: 95, name: "Şef Kokteyl", price: 150, category: "kokteyller", image: "images/sef-kokteyl.jpg", description: "Şef Kokteyl" }
];

let currentView = 'categories';
let selectedCategory = null;
